FROM deepmanager/base

RUN pip install --no-cache-dir http://download.pytorch.org/whl/cu91/torch-0.4.0-cp36-cp36m-linux_x86_64.whl \
    && pip install --no-cache-dir torchvision \
    && rm -rf /tmp/* /var/tmp/*